builtin_models:
  - id: builtin-llm-deepseek
    type: KnowledgeQA
    source: remote
    is_default: true
    name: ${LLM_MODEL_NAME}
    parameters:
      base_url: ${LLM_BASE_URL}
      api_key: ${LLM_API_KEY}
      provider: ${LLM_PROVIDER}

  - id: builtin-embedding-ollama
    type: Embedding
    source: local
    is_default: true
    name: ${EMBEDDING_MODEL_NAME}
    parameters:
      base_url: ${EMBEDDING_BASE_URL}
      api_key: ${EMBEDDING_API_KEY}
      provider: ${EMBEDDING_PROVIDER}
      embedding_parameters:
        dimension: 1024
        truncate_prompt_tokens: 0
      supports_dimension_override: false
      ollama_base_url: ${OLLAMA_BASE_URL}
      interface_type: ollama

  - id: builtin-rerank-jina
    type: Rerank
    source: remote
    is_default: false
    name: ${RERANK_MODEL_NAME}
    parameters:
      base_url: ${RERANK_BASE_URL}
      api_key: ${RERANK_API_KEY}
      provider: ${RERANK_PROVIDER}
